import type React from "react"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "DBC Point of Sale",
  description: "Generated by create next app",
}

import ClientLayout from "./ClientLayout"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <ClientLayout>{children}</ClientLayout>
}
